/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrame;

import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author AdhamFayrouz
 */
public class addCarPanel extends javax.swing.JPanel {

    /**
     * Creates new form addCarPanel
     */
    
    public addCarPanel() {
        initComponents();
        this.setVisible(false);
        color1Label.setVisible(false);
        color2Label.setVisible(false);
        color3Label.setVisible(false);
        color1field.setVisible(false);
        color2field.setVisible(false);
        color3field.setVisible(false);
    }
    
    public void clearForm(){
        manufTypefield.setText("");
        modelfield.setText("");
        yearfield.setText("");
        pricefield.setText("");
        colornumfield.setSelectedIndex(0);
        imgfield.setText("");
        color1field.setText("");
        color2field.setText("");
        color3field.setText("");
        color1field.setVisible(false);
        color2field.setVisible(false);
        color3field.setVisible(false);
        color1Label.setVisible(false);
        color2Label.setVisible(false);
        color3Label.setVisible(false);
    }
    
    public JTextField[] getTextFields(){
        JTextField[] texts = {manufTypefield,modelfield,yearfield,pricefield,imgfield,color1field,color2field,color3field};
        return texts;
    }
    public int getColorNumber(){
        return colornumfield.getSelectedIndex();
    }
    public void browseImage(){
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setAcceptAllFileFilterUsed(false);
        fileChooser.setFileFilter(new FileNameExtensionFilter("Images",ImageIO.getReaderFileSuffixes()));
        int choice = fileChooser.showOpenDialog(this);
        if(choice == JFileChooser.APPROVE_OPTION){
            File file = fileChooser.getSelectedFile();
            String filename = file.getAbsolutePath();
            imgfield.setText(filename);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addForm = new javax.swing.JPanel();
        price = new javax.swing.JLabel();
        modelName = new javax.swing.JLabel();
        modelfield = new javax.swing.JTextField();
        year_manufacture = new javax.swing.JLabel();
        colorNum = new javax.swing.JLabel();
        yearfield = new javax.swing.JTextField();
        manufacture_type = new javax.swing.JLabel();
        manufTypefield = new javax.swing.JTextField();
        pricefield = new javax.swing.JTextField();
        colornumfield = new javax.swing.JComboBox<>();
        imgfield = new javax.swing.JTextField();
        imgLabel = new javax.swing.JLabel();
        imgButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        color2Label = new javax.swing.JLabel();
        color2field = new javax.swing.JTextField();
        color1field = new javax.swing.JTextField();
        color3Label = new javax.swing.JLabel();
        color1Label = new javax.swing.JLabel();
        color3field = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(900, 900));

        addForm.setBackground(new java.awt.Color(0, 102, 102));

        price.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        price.setForeground(new java.awt.Color(240, 240, 240));
        price.setText("Price");

        modelName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        modelName.setForeground(new java.awt.Color(240, 240, 240));
        modelName.setText("Model Name");

        modelfield.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        modelfield.setName("model name"); // NOI18N
        modelfield.setPreferredSize(new java.awt.Dimension(264, 35));

        year_manufacture.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        year_manufacture.setForeground(new java.awt.Color(240, 240, 240));
        year_manufacture.setText("Year of Manufacture");

        colorNum.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        colorNum.setForeground(new java.awt.Color(240, 240, 240));
        colorNum.setText("Color Number");

        yearfield.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        yearfield.setName("year of manufacture"); // NOI18N

        manufacture_type.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        manufacture_type.setForeground(new java.awt.Color(240, 240, 240));
        manufacture_type.setText("Manufacture Type");

        manufTypefield.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        manufTypefield.setName("manufactureType"); // NOI18N
        manufTypefield.setPreferredSize(new java.awt.Dimension(264, 35));

        pricefield.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pricefield.setName("price"); // NOI18N

        colornumfield.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        colornumfield.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Color", "1", "2", "3" }));
        colornumfield.setName("color number"); // NOI18N
        colornumfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colornumfieldActionPerformed(evt);
            }
        });

        imgfield.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        imgfield.setName("Image"); // NOI18N

        imgLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        imgLabel.setForeground(new java.awt.Color(240, 240, 240));
        imgLabel.setText("Image");

        imgButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        imgButton.setText("Browse");

        addButton.setBackground(new java.awt.Color(0, 0, 153));
        addButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addButton.setForeground(new java.awt.Color(240, 240, 240));
        addButton.setText("Add Car");

        backButton.setBackground(new java.awt.Color(153, 0, 51));
        backButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        backButton.setForeground(new java.awt.Color(240, 240, 240));
        backButton.setText("Back");

        color2Label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        color2Label.setForeground(new java.awt.Color(240, 240, 240));
        color2Label.setText("Color 2");

        color2field.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        color2field.setName("second color"); // NOI18N

        color1field.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        color1field.setName("first color"); // NOI18N

        color3Label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        color3Label.setForeground(new java.awt.Color(240, 240, 240));
        color3Label.setText("Color 3");

        color1Label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        color1Label.setForeground(new java.awt.Color(240, 240, 240));
        color1Label.setText("Color 1");

        color3field.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        color3field.setName("third color"); // NOI18N

        javax.swing.GroupLayout addFormLayout = new javax.swing.GroupLayout(addForm);
        addForm.setLayout(addFormLayout);
        addFormLayout.setHorizontalGroup(
            addFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addFormLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(addFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addFormLayout.createSequentialGroup()
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addFormLayout.createSequentialGroup()
                        .addGroup(addFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(color1Label, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(color3Label, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(color2Label, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(addFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(color3field, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(color2field, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(color1field, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(addFormLayout.createSequentialGroup()
                        .addComponent(price)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pricefield, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addFormLayout.createSequentialGroup()
                        .addGroup(addFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(manufacture_type)
                            .addComponent(modelName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(addFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(manufTypefield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modelfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addFormLayout.createSequentialGroup()
                        .addGroup(addFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(year_manufacture)
                            .addComponent(colorNum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(addFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yearfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(colornumfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(addFormLayout.createSequentialGroup()
                        .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imgfield)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imgButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(161, 161, 161))
        );
        addFormLayout.setVerticalGroup(
            addFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addFormLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(addFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manufacture_type, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manufTypefield, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(addFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(addFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(year_manufacture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(addFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addFormLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(pricefield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(addFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(colorNum)
                    .addComponent(colornumfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(color1field, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(color1Label))
                .addGap(18, 18, 18)
                .addGroup(addFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(color2field, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(color2Label))
                .addGap(18, 18, 18)
                .addGroup(addFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(color3field, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(color3Label))
                .addGap(24, 24, 24)
                .addGroup(addFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(imgButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imgLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imgfield, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(addFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92))
        );

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADD FORM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(addForm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void colornumfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colornumfieldActionPerformed
        // TODO add your handling code here:
        if(colornumfield.getSelectedIndex()!=0){
            int colornum = colornumfield.getSelectedIndex();
            if(colornum ==1){
                color1Label.setVisible(true);
                color1field.setVisible(true);
                color2Label.setVisible(false);
                color2field.setVisible(false);
                color3Label.setVisible(false);
                color3field.setVisible(false);
            }
            else if(colornum == 2){
                color1Label.setVisible(true);
                color1field.setVisible(true);
                color2Label.setVisible(true);
                color2field.setVisible(true);
                color3Label.setVisible(false);
                color3field.setVisible(false);
            }
            else if(colornum==3){

                color1Label.setVisible(true);
                color1field.setVisible(true);
                color2Label.setVisible(true);
                color2field.setVisible(true);
                color3Label.setVisible(true);
                color3field.setVisible(true);
            }
        }
        else{
            color1Label.setVisible(false);
            color1field.setVisible(false);
            color2Label.setVisible(false);
            color2field.setVisible(false);
            color3Label.setVisible(false);
            color3field.setVisible(false);
        }
        
    }//GEN-LAST:event_colornumfieldActionPerformed
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton addButton;
    private javax.swing.JPanel addForm;
    public javax.swing.JButton backButton;
    private javax.swing.JLabel color1Label;
    private javax.swing.JTextField color1field;
    private javax.swing.JLabel color2Label;
    private javax.swing.JTextField color2field;
    private javax.swing.JLabel color3Label;
    private javax.swing.JTextField color3field;
    private javax.swing.JLabel colorNum;
    private javax.swing.JComboBox<String> colornumfield;
    public javax.swing.JButton imgButton;
    private javax.swing.JLabel imgLabel;
    public javax.swing.JTextField imgfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField manufTypefield;
    private javax.swing.JLabel manufacture_type;
    private javax.swing.JLabel modelName;
    private javax.swing.JTextField modelfield;
    private javax.swing.JLabel price;
    private javax.swing.JTextField pricefield;
    private javax.swing.JLabel year_manufacture;
    private javax.swing.JTextField yearfield;
    // End of variables declaration//GEN-END:variables
}
