/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrame;

import carsalessystem.Car;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author AdhamFayrouz
 */
public class editCarPanel extends javax.swing.JPanel {

    /**
     * Creates new form editCarPanel
     */
    public editCarPanel() {
        initComponents();
        this.setVisible(false);
    }
    
    public void clearForm(){
        manufTypefield.setText("");
        modelfield.setText("");
        yearfield.setText("");
        pricefield.setText("");
        imgfield.setText("");
    }
    
    public JTextField[] getTextFields(){
        JTextField[] texts = {manufTypefield,modelfield,yearfield,pricefield,imgfield};
        return texts;
    }
    
    public void setTextFields (Car car){
        manufTypefield.setText(car.getManufactor_Type());
        modelfield.setText(car.getModel_Name());
        yearfield.setText(String.valueOf(car.getYear_manufacture()));
        pricefield.setText(String.valueOf(car.getPrice()));
    }
    public void browseImage(){
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setAcceptAllFileFilterUsed(false);
        fileChooser.setFileFilter(new FileNameExtensionFilter("Images",ImageIO.getReaderFileSuffixes()));
        int choice = fileChooser.showOpenDialog(this);
        if(choice == JFileChooser.APPROVE_OPTION){
            File file = fileChooser.getSelectedFile();
            String filename = file.getAbsolutePath();
            imgfield.setText(filename);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editForm = new javax.swing.JPanel();
        price = new javax.swing.JLabel();
        modelName = new javax.swing.JLabel();
        modelfield = new javax.swing.JTextField();
        year_manufacture = new javax.swing.JLabel();
        yearfield = new javax.swing.JTextField();
        manufacture_type = new javax.swing.JLabel();
        manufTypefield = new javax.swing.JTextField();
        pricefield = new javax.swing.JTextField();
        imgfield = new javax.swing.JTextField();
        imgLabel = new javax.swing.JLabel();
        imgButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        editBar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(900, 900));

        editForm.setBackground(new java.awt.Color(0, 102, 102));

        price.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        price.setForeground(new java.awt.Color(240, 240, 240));
        price.setText("Price");

        modelName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        modelName.setForeground(new java.awt.Color(240, 240, 240));
        modelName.setText("Model Name");

        modelfield.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        modelfield.setName("model name"); // NOI18N
        modelfield.setPreferredSize(new java.awt.Dimension(264, 35));

        year_manufacture.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        year_manufacture.setForeground(new java.awt.Color(240, 240, 240));
        year_manufacture.setText("Year of Manufacture");

        yearfield.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        yearfield.setName("year of manufacture"); // NOI18N

        manufacture_type.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        manufacture_type.setForeground(new java.awt.Color(240, 240, 240));
        manufacture_type.setText("Manufacture Type");

        manufTypefield.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        manufTypefield.setName("manufactureType"); // NOI18N
        manufTypefield.setPreferredSize(new java.awt.Dimension(264, 35));

        pricefield.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pricefield.setName("price"); // NOI18N

        imgfield.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        imgfield.setName("Image"); // NOI18N

        imgLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        imgLabel.setForeground(new java.awt.Color(240, 240, 240));
        imgLabel.setText("Image");

        imgButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        imgButton.setText("Browse");

        editButton.setBackground(new java.awt.Color(0, 0, 153));
        editButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        editButton.setForeground(new java.awt.Color(240, 240, 240));
        editButton.setText("Edit Car");

        backButton.setBackground(new java.awt.Color(153, 0, 51));
        backButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        backButton.setForeground(new java.awt.Color(240, 240, 240));
        backButton.setText("Back");

        javax.swing.GroupLayout editFormLayout = new javax.swing.GroupLayout(editForm);
        editForm.setLayout(editFormLayout);
        editFormLayout.setHorizontalGroup(
            editFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editFormLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(editFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(editFormLayout.createSequentialGroup()
                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(editFormLayout.createSequentialGroup()
                        .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imgfield, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imgButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, editFormLayout.createSequentialGroup()
                        .addGroup(editFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(manufacture_type, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modelName)
                            .addComponent(price)
                            .addComponent(year_manufacture))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(editFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pricefield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(editFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(modelfield, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(manufTypefield, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(yearfield, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(120, 120, 120))
        );
        editFormLayout.setVerticalGroup(
            editFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editFormLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addGroup(editFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manufacture_type, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manufTypefield, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(editFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(editFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(yearfield)
                    .addComponent(year_manufacture, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(editFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pricefield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(imgfield, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imgButton)
                    .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(editFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(318, 318, 318))
        );

        editBar.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        editBar.setForeground(new java.awt.Color(255, 255, 255));
        editBar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editBar.setText("Edit Form");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(editForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editBar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton backButton;
    private javax.swing.JLabel editBar;
    public javax.swing.JButton editButton;
    private javax.swing.JPanel editForm;
    public javax.swing.JButton imgButton;
    private javax.swing.JLabel imgLabel;
    public javax.swing.JTextField imgfield;
    private javax.swing.JTextField manufTypefield;
    private javax.swing.JLabel manufacture_type;
    private javax.swing.JLabel modelName;
    private javax.swing.JTextField modelfield;
    private javax.swing.JLabel price;
    private javax.swing.JTextField pricefield;
    private javax.swing.JLabel year_manufacture;
    private javax.swing.JTextField yearfield;
    // End of variables declaration//GEN-END:variables
}
