/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrame;

import javax.swing.JTextField;



/**
 *
 * @author AdhamFayrouz
 */
public class regPanel extends javax.swing.JPanel {

    /**
     * Creates new form regPanel
     */
    
    public regPanel() {
        initComponents();
        this.setVisible(false);
         
    }
    
    public JTextField[] getTextFields(){
        JTextField [] texts = {namefield,emailfield,passfield,addressfield,phonefield};
        return texts;
    }
    
    public void clearForm() {
        namefield.setText("");
        emailfield.setText("");
        passfield.setText("");
        addressfield.setText("");
        phonefield.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regForm = new javax.swing.JPanel();
        address = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        emailfield = new javax.swing.JTextField();
        password = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        phonefield = new javax.swing.JTextField();
        regButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        addressfield = new javax.swing.JTextField();
        passfield = new javax.swing.JPasswordField();
        name = new javax.swing.JLabel();
        namefield = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 0, 102));
        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setPreferredSize(new java.awt.Dimension(900, 900));

        regForm.setBackground(new java.awt.Color(0, 0, 0));

        address.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        address.setForeground(new java.awt.Color(240, 240, 240));
        address.setText("Address");

        email.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        email.setForeground(new java.awt.Color(240, 240, 240));
        email.setText("Email");

        emailfield.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        emailfield.setName("email"); // NOI18N
        emailfield.setPreferredSize(new java.awt.Dimension(264, 35));

        password.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        password.setForeground(new java.awt.Color(240, 240, 240));
        password.setText("Password");

        phone.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        phone.setForeground(new java.awt.Color(240, 240, 240));
        phone.setText("Phone Number");

        phonefield.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        phonefield.setName("phoneNumber"); // NOI18N

        regButton.setBackground(new java.awt.Color(102, 153, 255));
        regButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        regButton.setForeground(new java.awt.Color(240, 240, 240));
        regButton.setText("Register");

        backButton.setBackground(new java.awt.Color(153, 0, 51));
        backButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        backButton.setForeground(new java.awt.Color(240, 240, 240));
        backButton.setText("Back To Login");

        addressfield.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addressfield.setName("address"); // NOI18N

        passfield.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        passfield.setName("password"); // NOI18N

        name.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        name.setForeground(new java.awt.Color(240, 240, 240));
        name.setText("Name");

        namefield.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        namefield.setName("name"); // NOI18N
        namefield.setPreferredSize(new java.awt.Dimension(264, 35));

        javax.swing.GroupLayout regFormLayout = new javax.swing.GroupLayout(regForm);
        regForm.setLayout(regFormLayout);
        regFormLayout.setHorizontalGroup(
            regFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, regFormLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(regFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, regFormLayout.createSequentialGroup()
                        .addGroup(regFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email))
                        .addGap(105, 105, 105)
                        .addGroup(regFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(namefield, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(emailfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, regFormLayout.createSequentialGroup()
                        .addComponent(password)
                        .addGap(74, 74, 74)
                        .addComponent(passfield, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, regFormLayout.createSequentialGroup()
                        .addComponent(regButton, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(regFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(regFormLayout.createSequentialGroup()
                            .addComponent(address)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addressfield, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, regFormLayout.createSequentialGroup()
                            .addComponent(phone)
                            .addGap(18, 18, 18)
                            .addComponent(phonefield, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(220, 220, 220))
        );
        regFormLayout.setVerticalGroup(
            regFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regFormLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(regFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(namefield, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(regFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(regFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passfield)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(regFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addressfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(regFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phonefield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phone))
                .addGap(37, 37, 37)
                .addGroup(regFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(341, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registration Form");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(regForm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JTextField addressfield;
    public javax.swing.JButton backButton;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel name;
    private javax.swing.JTextField namefield;
    private javax.swing.JPasswordField passfield;
    private javax.swing.JLabel password;
    private javax.swing.JLabel phone;
    private javax.swing.JTextField phonefield;
    public javax.swing.JButton regButton;
    private javax.swing.JPanel regForm;
    // End of variables declaration//GEN-END:variables
}
